MusicApp/config/routes.rb
Rails.application.routes.draw do

  resources :users
  resource :session, only: [:new, :create, :destroy]

  root :to => "users#show"

end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/user.rb
# require 'bcrypt'

class User < ApplicationRecord

  validates :email, :session_token, :password_digest, presence: true
  validates :email, :session_token, :password_digest, uniqueness: true
  validates :password, length: { minimum: 6 }, allow_nil: true
  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user.is_password?(password)
  end

  def reset_sesson_token!
    self.session_token = User.generate_session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end


end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in? 

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!curent_user
  end

  def log_in_user!(user)
    user.reset_sesson_token!
    session[:session_token] = user.session_token
  end

  protected

  def user_params
    params.require(:user).permit(:email, :password)
  end


end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:user][:email], user_params[:user][:password])
    if @user
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = "User not recognized"
      render :new
    end
  end

  def destroy
    session[:session_token] = nil
  end

end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render :index
  end

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = 'Invalid email or password'
      render :new
    end
  end

end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/layouts/_form.html.erb
<form action="/users" method="post">

  <label for="email">Email:</label>
  <input id="email" type="text" name="user[email]">

  <br><br>

  <label for="password">Password:</label>
  <input id="password" type="text" name="user[password]">

  <br><br>

  <input type="submit" value="Sign up">
</form>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html> <html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <a href="#">Log out</a>
    <% else %>
      <a href="<%= new_user_url %>">Sign up</a>
      <a href="<%= new_session_url %>">Log in</a>
    <% end %>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/shared/_form.html.erb
<form action="/users" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="email">Email:</label>
  <input id="email" type="text" name="user[email]">

  <br><br>

  <label for="password">Password:</label>
  <input id="password" type="text" name="user[password]">

  <br><br>

  <input type="submit" value="Sign up">
</form>

MusicApp/app/views/users/index.html.erb
<h1>User index</h1>

MusicApp/app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= render "shared/form" %>

MusicApp/app/views/users/show.html.erb
<h1>Music stuff</h1>